# Compound Image Folder Mapping

In [1]:
from zebrafish_notebook_utils import build_compound_image_index, build_compound_image_run_map

In [2]:
compound_image_map_df = build_compound_image_run_map()
compound_image_index_df = build_compound_image_index(compound_image_map_df)

compound_image_map_df.to_csv("compound_image_run_map.csv", index=False)
compound_image_index_df.to_csv("compound_image_index.csv", index=False)

compound_image_map_df.head(20)

,compound,compound_class,mechanism_of_action,image_run_dir,image_run_dir_relative,source_batch,dir_name,folder_status
0,(RS)-(Tetrazol-5-yl)glycine,Glutamate agonists,NMDAR_Activation,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,FOURTH BATCH 2018/Rs tetrazol Glycine (RsT) Ru...,FOURTH BATCH 2018,Rs tetrazol Glycine (RsT) Run 1 21 aug 2018,active
1,(RS)-(Tetrazol-5-yl)glycine,Glutamate agonists,NMDAR_Activation,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,FOURTH BATCH 2018/Rs tetrazol Glycine (RsT) Ru...,FOURTH BATCH 2018,Rs tetrazol Glycine (RsT) Run 2 24 Aug 2018,active
2,4-Aminophenyl sulfone,"Mixed classes, no known link to seizures",SulfonamideLike_Antibiotic,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...,THIRD BATCH convulsants/4 aminophenyl sulfone ...,THIRD BATCH convulsants,4 aminophenyl sulfone run 2 24 july 2017,active
3,4-Aminophenyl sulfone,"Mixed classes, no known link to seizures",SulfonamideLike_Antibiotic,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...,THIRD BATCH convulsants/4 aminophenyl sulfone ...,THIRD BATCH convulsants,4 aminophenyl sulfone run1 23 July 2017,active
4,4-aminopyridine,K+ channel blockers,Kv_Blocker_NonSelective,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FIR...,FIRST BATCH convulsants/Brain_Imaging_Rerun_-_...,FIRST BATCH convulsants,4AP_0.2OD,active
5,4-aminopyridine,K+ channel blockers,Kv_Blocker_NonSelective,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FIR...,FIRST BATCH convulsants/Brain_Imaging_Rerun_-_...,FIRST BATCH convulsants,4AP_Round2_0.2OD,active
6,4-aminopyridine,K+ channel blockers,Kv_Blocker_NonSelective,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,FOURTH BATCH 2018/4-Aminopyridine ReRun 1 28 J...,FOURTH BATCH 2018,4-Aminopyridine ReRun 1 28 Jan 2019,active
7,4-aminopyridine,K+ channel blockers,Kv_Blocker_NonSelective,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,FOURTH BATCH 2018/4-Aminopyridine ReRun 2 20 J...,FOURTH BATCH 2018,4-Aminopyridine ReRun 2 20 Jan 2019,active
8,Aminophylline,Methylxanthine derivatives,P1_Antagonist_PDE_Inhibitor,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/SEC...,SECOND BATCH convulsants/Aminophylline 24 nov ...,SECOND BATCH convulsants,Aminophylline 24 nov 2016,active
9,Aminophylline,Methylxanthine derivatives,P1_Antagonist_PDE_Inhibitor,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/SEC...,SECOND BATCH convulsants/Aminophylline 30 nove...,SECOND BATCH convulsants,Aminophylline 30 nove 2016,active
10,Amitriptyline,Tricyclic antidepressants,NET_SERT_ReuptakeInhibitor_MultiReceptorAntago...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,FOURTH BATCH 2018/Amitripityline Run 1 12 Feb ...,FOURTH BATCH 2018,Amitripityline Run 1 12 Feb 2018,active
11,Amitriptyline,Tricyclic antidepressants,NET_SERT_ReuptakeInhibitor_MultiReceptorAntago...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,FOURTH BATCH 2018/Amitriptyline Run 2 13 Feb 2018,FOURTH BATCH 2018,Amitriptyline Run 2 13 Feb 2018,active
12,Amitriptyline,Tricyclic antidepressants,NET_SERT_ReuptakeInhibitor_MultiReceptorAntago...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,FOURTH BATCH 2018/Amitriptyline Run1 analysed ...,FOURTH BATCH 2018,Amitriptyline Run1 analysed by old script DONT...,do_not_use
13,Amoxapine,Tricyclic antidepressants,NET_SERT_ReuptakeInhibitor_MultiReceptorAntago...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,FOURTH BATCH 2018/Amoxipine Run 2 23 jan 2018,FOURTH BATCH 2018,Amoxipine Run 2 23 jan 2018,active
14,Amoxapine,Tricyclic antidepressants,NET_SERT_ReuptakeInhibitor_MultiReceptorAntago...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,FOURTH BATCH 2018/Amoxipine run 1 22 jan 2018,FOURTH BATCH 2018,Amoxipine run 1 22 jan 2018,active
15,Amphetamine,Illicit drugs,DAT_NET_SERT_ReuptakeInhibitor,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,FOURTH BATCH 2018/Amphetamine Run 1 19 feb 2018,FOURTH BATCH 2018,Amphetamine Run 1 19 feb 2018,active
16,Amphetamine,Illicit drugs,DAT_NET_SERT_ReuptakeInhibitor,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,FOURTH BATCH 2018/Amphetamine Run 2 20 Feb 2018,FOURTH BATCH 2018,Amphetamine Run 2 20 Feb 2018,active
17,Apomorphine,"Mixed classes, unclear link to seizures",D1_D2R_5HTR_aR_Agonist,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...,THIRD BATCH convulsants/EMETIC COMPOUNDS NOT C...,THIRD BATCH convulsants,Apomorphine run 1 22 aug 2017,active
18,Apomorphine,"Mixed classes, unclear link to seizures",D1_D2R_5HTR_aR_Agonist,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...,THIRD BATCH convulsants/EMETIC COMPOUNDS NOT C...,THIRD BATCH convulsants,Apomorphine run 2 23 Aug 2017,active
19,Apomorphine,"Mixed classes, unclear link to seizures",D1_D2R_5HTR_aR_Agonist,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...,THIRD BATCH convulsants/EMETICS RERUN/Apomorph...,THIRD BATCH convulsants,Apomorphine run 1 22 aug 2017 DONE,active

In [3]:
compound_image_index_df.head(20)

,compound,compound_class,mechanism_of_action,n_image_run_dirs,n_active_image_run_dirs,image_run_dirs,active_image_run_dirs
0,(RS)-(Tetrazol-5-yl)glycine,Glutamate agonists,NMDAR_Activation,2,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...
1,4-Aminophenyl sulfone,"Mixed classes, no known link to seizures",SulfonamideLike_Antibiotic,2,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...
2,4-aminopyridine,K+ channel blockers,Kv_Blocker_NonSelective,4,4,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FIR...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FIR...
3,Aminophylline,Methylxanthine derivatives,P1_Antagonist_PDE_Inhibitor,2,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/SEC...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/SEC...
4,Amitriptyline,Tricyclic antidepressants,NET_SERT_ReuptakeInhibitor_MultiReceptorAntago...,3,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...
5,Amoxapine,Tricyclic antidepressants,NET_SERT_ReuptakeInhibitor_MultiReceptorAntago...,2,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...
6,Amphetamine,Illicit drugs,DAT_NET_SERT_ReuptakeInhibitor,2,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...
7,Apomorphine,"Mixed classes, unclear link to seizures",D1_D2R_5HTR_aR_Agonist,4,4,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...
8,BW373U86,Opioid analgesics,DOR_Agonist,2,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...
9,Bemegride,Analeptics,GABAAR_Antagonist,2,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...
10,Bethanechol,Muscarinic agonists,mAChR_Agonist_NonSelective,2,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...
11,Bicuculline,Analeptics,GABAAR_Antagonist,2,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...
12,Bupropion,NDRI Antidepressant,NET_DAT_ReuptakeInhibitor,2,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/SEC...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/SEC...
13,Caffeine,Methylxanthine derivatives,P1_Antagonist_PDE_Inhibitor,5,4,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...
14,Carbachol,Muscarinic agonists,mAChR_nAChR_Agonist,2,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...
15,Chlorpromazine,Phenothiazine antipsychotic,D1_D2_D3_D4R_MultiReceptorAntagonist,2,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...
16,Cis-ACPD,Glutamate agonists,NMDAR_Activation,2,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...
17,Cisplatin,"Mixed classes, no known link to seizures",DNA_CrossLinking_Chemotherapeutic,3,3,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...
18,Clomipramine,Tricyclic antidepressants,NET_SERT_ReuptakeInhibitor_MultiReceptorAntago...,2,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/FOU...
19,Clonidine,"Mixed classes, no known link to seizures",a2R_Agonist_CNS,2,2,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...,/mnt/tyler/Matt Winter/BRAIN IMAGES BACKUP/THI...